server.port: 8020

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/distribuida?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: alex
    password: jeame
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/