server.port: 8010
app.queueName: distribuida

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/distribuida?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: alex
    password: jeame
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  cloud:
      stream:
        bindings:
          employeeRegistrationChannel:
            destination: employeeRegistrations
        default:
          contentType: application/json
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false
    scheduler:
      persistence:
        enabled: false
        redis:
          embedded: false
          enabled: false

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/